#!/bin/bash
#
# Usage:
#  clean
#
# Removes all generated packages and intermediate artifacts from the filesystem.
#


main()
{
  rm --force --recursive scratch/* packages/*
  docker rmi $(docker images --quiet --filter reference=irods-plugin-build)
}


main
