#!/bin/bash
#
# Usage:
#  clean
#
# Removes all generated packages and intermediate artifacts from the filesystem.
#


main()
{
  local baseDir=$(dirname $(readlink --canonicalize "$0"))

  rm --force --recursive "$baseDir"/packages "$baseDir"/scratch 
  docker images --quiet --filter reference=irods-plugin-build | xargs --no-run-if-empty docker rmi
}


main
