FROM centos:7
MAINTAINER tedgin@cyverse.org

RUN yum --assumeyes install \
      gcc-c++ libcurl-devel make rpm-build \
      ftp://ftp.renci.org/pub/irods/releases/4.1.10/centos7/irods-dev-4.1.10-centos7-x86_64.rpm \
      ftp://ftp.renci.org/pub/irods/releases/4.1.10/centos7/irods-runtime-4.1.10-centos7-x86_64.rpm && \
    mkdir /rpmbuild /src && \
    chmod a+w /rpmbuild

VOLUME /src

WORKDIR /src

CMD bash
