FROM centos:6
MAINTAINER tedgin@cyverse.org

RUN yum --assumeyes install \
      gcc-c++ libcurl-devel rpm-build \
      ftp://ftp.renci.org/pub/irods/releases/4.1.10/centos6/irods-dev-4.1.10-centos6-x86_64.rpm \
      ftp://ftp.renci.org/pub/irods/releases/4.1.10/centos6/irods-runtime-4.1.10-centos6-x86_64.rpm && \
    mkdir /rpmbuild /src && \
    chmod a+w /rpmbuild

VOLUME /src

WORKDIR /src

CMD bash
